global:

  # ImagePullSecrets for control plane ServiceAccount, list of secrets in the same namespace
  # to use for pulling any images in pods that reference this ServiceAccount.
  # Must be set for any cluster configured with private docker registry.
  imagePullSecrets: []

  # Used to locate istiod.
  istioNamespace: istio-system

  istiod:
    enableAnalysis: false

  configValidation: true
  externalIstiod: false
  remotePilotAddress: ""

base:
  # Used for helm2 to add the CRDs to templates.
  enableCRDTemplates: false

  # Validation webhook configuration url
  # For example: https://$remotePilotAddress:15017/validate
  validationURL: ""

  validationWebhook:
    # Refer to the [kubernetes LabelSelector API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#labelselector-v1-meta)
    namespaceSelector:
      matchLabels: {}
      matchExpressions: []

  # For istioctl usage to disable istio config crds in base
  enableIstioConfigCRDs: true
